# .tbls.yml

# DSN (Database Source Name) to connect database
dsn: postgres://postgres:mysecretpassword@localhost:5432/mydb?sslmode=disable

# Filter
exclude:
  - _prisma_migrations

# Linter settings
lint:
  requireColumnComment:
    enabled: true
    exclude:
      - id
      - created
      - updated
  columnCount:
    enabled: true
    max: 10
